"""Prove the generated gRPC stubs are real and complete.

The stubs are generated by conftest.py (never committed by hand). This test:
  - imports both stub modules from the `proto` package,
  - instantiates every message declared in cognos.proto (round-trip serialized),
  - verifies the CognosIpc service stub exposes exactly the 7 documented RPCs.
"""
import grpc
import pytest

from proto import cognos_pb2, cognos_pb2_grpc

# Every top-level message declared in ipc/grpc/proto/cognos.proto.
ALL_MESSAGES = [
    "Envelope",
    "Intent",
    "IntentResponse",
    "MemoryQuery",
    "MemoryResult",
    "HalGateRequest",
    "HalGateResponse",
    "ResourceHint",
    "Heartbeat",
    "Event",
    "CapabilityViolation",
    "PipelineMetricsRequest",
    "PipelineMetrics",
]

# The 7 RPCs on service CognosIpc.
RPC_METHODS = [
    "DispatchIntent",
    "QueryMemory",
    "HalGate",
    "ResourceHint",
    "Heartbeat",
    "StreamEvents",
    "GetPipelineMetrics",
]


@pytest.mark.parametrize("name", ALL_MESSAGES)
def test_message_instantiates_and_roundtrips(name):
    msg_cls = getattr(cognos_pb2, name)
    instance = msg_cls()
    # Serialize + parse back to prove the descriptor is fully wired.
    parsed = msg_cls.FromString(instance.SerializeToString())
    assert parsed is not None


def test_nested_memory_result_hit():
    hit = cognos_pb2.MemoryResult.Hit(object_id="obj-1", score=0.5)
    assert hit.object_id == "obj-1"
    assert hit.score == pytest.approx(0.5)


def test_populated_message_fields_roundtrip():
    intent = cognos_pb2.Intent(
        intent_id="i-1",
        action="file.open",
        confidence=0.9,
        requires=["file.read"],
    )
    restored = cognos_pb2.Intent.FromString(intent.SerializeToString())
    assert restored.intent_id == "i-1"
    assert restored.action == "file.open"
    assert restored.confidence == pytest.approx(0.9)
    assert list(restored.requires) == ["file.read"]


def test_service_stub_exposes_all_rpc_methods():
    channel = grpc.insecure_channel("localhost:1")
    try:
        stub = cognos_pb2_grpc.CognosIpcStub(channel)
        for method in RPC_METHODS:
            assert hasattr(stub, method), f"stub is missing RPC method {method}"
    finally:
        channel.close()


def test_service_declares_all_rpcs():
    service = cognos_pb2.DESCRIPTOR.services_by_name["CognosIpc"]
    declared = {m.name for m in service.methods}
    assert declared == set(RPC_METHODS)
