//! Local LLM inference engine — wraps llama.cpp via FFI, providing synchronous
//! and streaming completion APIs with token-level cancellation.
//!
//! The [`InferenceEngine`] is the top-level entry point used by the COGNOS
//! scheduler and the agents themselves. It owns a [`ModelPool`] so that many
//! conversations can share resident weights, and it tracks in-flight requests
//! so that a [`cancel`] call can stop generation mid-token.
//!
//! [`cancel`]: InferenceEngine::cancel

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use futures::stream::{self, Stream, StreamExt};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::sync::Mutex;
use tracing::{debug, error, info, warn};
use uuid::Uuid;

use crate::bindings::Token;
use crate::context::LlmContext;
use crate::model_pool::{ModelId, ModelPool, PoolError};

// ─── Errors ────────────────────────────────────────────────────────────────

/// Errors that can be returned by the inference engine.
#[derive(Debug, Error, Serialize, Deserialize, Clone)]
pub enum InferenceError {
    /// No model matching the request is currently loaded in the pool.
    #[error("no model loaded for the requested id")]
    ModelNotLoaded,

    /// The backend ran out of memory while allocating KV cache or logits.
    #[error("out of memory during inference")]
    Oom,

    /// The request was cancelled by the caller before finishing.
    #[error("inference request cancelled")]
    Canceled,

    /// The underlying llama.cpp backend returned an error.
    #[error("backend error: {0}")]
    BackendError(String),

    /// The caller supplied parameters that the engine refused to apply.
    #[error("invalid inference parameters")]
    InvalidParams,
}

impl From<PoolError> for InferenceError {
    fn from(err: PoolError) -> Self {
        match err {
            PoolError::NotFound => InferenceError::ModelNotLoaded,
            PoolError::Oom => InferenceError::Oom,
            PoolError::LoadFailed => InferenceError::BackendError(err.to_string()),
            PoolError::StillReferenced => {
                InferenceError::BackendError("model still referenced".into())
            }
        }
    }
}

// ─── Finish Reason ─────────────────────────────────────────────────────────

/// Why generation stopped for a given completion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {
    /// A stop sequence was matched or the model emitted an EOS token.
    Stop,
    /// `max_tokens` was reached before the model stopped naturally.
    Length,
    /// The caller cancelled the request via [`InferenceEngine::cancel`].
    Cancelled,
    /// An error occurred during generation; see the logs for details.
    Error,
}

impl Default for FinishReason {
    fn default() -> Self {
        FinishReason::Stop
    }
}

// ─── Inference Params ──────────────────────────────────────────────────────

/// Per-request sampling and generation parameters.
///
/// All fields are `Option`-friendly at the engine level: when a field is left
/// `None`, the engine falls back to [`InferenceEngine::default_params`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferenceParams {
    /// Sampling temperature. Higher = more random. Typical range `0.0..=1.5`.
    pub temperature: f32,
    /// Nucleus sampling cumulative probability cap (`0.0..=1.0`).
    pub top_p: f32,
    /// Top-K sampling — only the K most likely tokens are considered.
    pub top_k: u32,
    /// Maximum number of tokens to generate before forcing a stop.
    pub max_tokens: u32,
    /// Strings that, once generated, terminate decoding immediately.
    pub stop_sequences: Vec<String>,
    /// PRNG seed for reproducible sampling. `None` picks a fresh seed.
    pub seed: Option<u64>,
}

impl Default for InferenceParams {
    fn default() -> Self {
        Self {
            temperature: 0.7,
            top_p: 0.9,
            top_k: 40,
            max_tokens: 512,
            stop_sequences: Vec::new(),
            seed: None,
        }
    }
}

// ─── Completion ────────────────────────────────────────────────────────────

/// The full result of a non-streaming completion request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Completion {
    /// Decoded UTF-8 text emitted by the model.
    pub text: String,
    /// Token ids generated by the model (excluding the prompt).
    pub tokens: Vec<Token>,
    /// Number of tokens in the prompt that were consumed.
    pub prompt_tokens: u32,
    /// Why generation stopped.
    pub finish_reason: FinishReason,
    /// Wall-clock time spent decoding, excluding prompt processing.
    pub elapsed: Duration,
}

impl Default for Completion {
    fn default() -> Self {
        Self {
            text: String::new(),
            tokens: Vec::new(),
            prompt_tokens: 0,
            finish_reason: FinishReason::default(),
            elapsed: Duration::default(),
        }
    }
}

// ─── Streaming Token ───────────────────────────────────────────────────────

/// A single streamed token. Re-exported from `bindings` for API ergonomics.
pub type StreamToken = Token;

/// Identifier handed back to the caller when a request is started, so that it
/// can later be cancelled via [`InferenceEngine::cancel`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RequestId(pub Uuid);

impl RequestId {
    /// Mint a fresh, globally-unique request id.
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for RequestId {
    fn default() -> Self {
        Self::new()
    }
}

// ─── In-Flight Request Tracking ────────────────────────────────────────────

/// Internal book-keeping for a single active inference request.
#[derive(Debug)]
struct InFlightRequest {
    /// Set to `true` by [`InferenceEngine::cancel`]; the decode loop polls it
    /// between tokens and aborts when it observes the flag.
    cancel_requested: bool,
    /// Time the request was first observed by the engine.
    started_at: Instant,
}

impl Default for InFlightRequest {
    fn default() -> Self {
        Self {
            cancel_requested: false,
            started_at: Instant::now(),
        }
    }
}

// ─── Inference Engine ──────────────────────────────────────────────────────

/// High-level local LLM inference engine.
///
/// Owns a [`ModelPool`] so that multiple agents can share resident weights,
/// tracks in-flight requests for cancellation, and exposes both buffered
/// ([`complete`]) and streaming ([`complete_stream`]) completion APIs.
///
/// [`complete`]: InferenceEngine::complete
/// [`complete_stream`]: InferenceEngine::complete_stream
pub struct InferenceEngine {
    /// Pool of loaded GGUF models, shared by all callers.
    models: ModelPool,
    /// Parameters used when the caller does not supply overrides.
    default_params: InferenceParams,
    /// In-flight requests keyed by [`RequestId`], guarded for concurrent
    /// mutation by `cancel` and the decode loop.
    in_flight: Arc<Mutex<HashMap<RequestId, InFlightRequest>>>,
}

impl InferenceEngine {
    /// Construct a new engine backed by the given model pool.
    pub fn new(models: ModelPool) -> Self {
        Self {
            models,
            default_params: InferenceParams::default(),
            in_flight: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Replace the engine-wide default parameters.
    pub fn with_default_params(mut self, params: InferenceParams) -> Self {
        self.default_params = params;
        self
    }

    /// Return a snapshot of the current default parameters.
    pub fn default_params(&self) -> &InferenceParams {
        &self.default_params
    }

    /// Borrow the underlying model pool. Used by callers that need to load
    /// or evict models explicitly.
    pub fn models(&self) -> &ModelPool {
        &self.models
    }

    /// Mutable borrow of the underlying model pool.
    pub fn models_mut(&mut self) -> &mut ModelPool {
        &mut self.models
    }

    /// Buffer a full completion and return it once the model stops.
    ///
    /// `params` overrides the engine defaults field-by-field. If `None`, the
    /// engine's [`default_params`] are used.
    ///
    /// [`default_params`]: InferenceEngine::default_params
    pub async fn complete(
        &self,
        _prompt: &str,
        _params: Option<InferenceParams>,
    ) -> Result<Completion, InferenceError> {
        let request_id = RequestId::new();
        {
            let mut guard = self.in_flight.lock().await;
            guard.insert(request_id.clone(), InFlightRequest::default());
        }

        info!(request_id = %request_id.0, "starting completion");
        debug!("complete() not yet implemented in v0 stub");

        // TODO(v1): acquire model from pool, build/attach LlmContext, tokenize
        // prompt, drive the decode loop polling `cancel_requested`, and emit a
        // real Completion.
        self.in_flight.lock().await.remove(&request_id);
        Err(InferenceError::BackendError(
            "complete() not implemented in v0 stub".into(),
        ))
    }

    /// Stream tokens to the caller as they are decoded.
    ///
    /// The returned stream yields [`Result<Token, InferenceError>`] items; the
    /// final item before `None` may carry [`InferenceError::Canceled`] if the
    /// caller invoked [`cancel`] for this request.
    ///
    /// [`cancel`]: InferenceEngine::cancel
    pub async fn complete_stream(
        &self,
        _prompt: &str,
        _params: Option<InferenceParams>,
    ) -> impl Stream<Item = Result<Token, InferenceError>> {
        let request_id = RequestId::new();
        {
            let mut guard = self.in_flight.lock().await;
            guard.insert(request_id.clone(), InFlightRequest::default());
        }

        info!(request_id = %request_id.0, "starting streaming completion");
        warn!("complete_stream() returns an empty stream in v0 stub");

        // TODO(v1): build an async channel-backed stream that the synchronous
        // decode loop feeds tokens into. For v0 we return an empty stream so
        // the public API shape is stable.
        let in_flight = Arc::clone(&self.in_flight);
        stream::once(async move {
            in_flight.lock().await.remove(&request_id);
            Err(InferenceError::BackendError(
                "complete_stream() not implemented in v0 stub".into(),
            ))
        })
        .map(|res| res)
    }

    /// Request cancellation of an in-flight request.
    ///
    /// Returns `Ok(())` even if the request has already completed — callers
    /// should treat this as best-effort. Returns
    /// [`InferenceError::Canceled`] is *not* returned here; the *result* of
    /// the request will reflect cancellation.
    pub async fn cancel(&self, request_id: RequestId) -> Result<(), InferenceError> {
        let mut guard = self.in_flight.lock().await;
        if let Some(req) = guard.get_mut(&request_id) {
            req.cancel_requested = true;
            info!(request_id = %request_id.0, "cancellation requested");
            Ok(())
        } else {
            warn!(request_id = %request_id.0, "cancel() called for unknown request");
            // Idempotent: treat as success.
            Ok(())
        }
    }

    /// Returns a borrowed view of an [`LlmContext`] for a given model.
    ///
    /// In v0 this is a placeholder; v1 will look up a per-session context
    /// from the engine's context table.
    pub fn context_for(&self, _model_id: &ModelId) -> Option<&LlmContext> {
        // TODO(v1): maintain a per-session context table.
        error!("context_for() not implemented in v0 stub");
        None
    }
}

impl Default for InferenceEngine {
    fn default() -> Self {
        Self::new(ModelPool::default())
    }
}

// ─── Drop ──────────────────────────────────────────────────────────────────

impl Drop for InferenceEngine {
    fn drop(&mut self) {
        // Best-effort: nothing to release at v0 since the pool owns handles.
        debug!("InferenceEngine dropped");
    }
}

// v0: stub implementation
