# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cognos_pb2 as cognos__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cognos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CognosIpcStub:
    """─── Top-level service ───────────────────────────────────────────────────────
    CognosIpc is the single gRPC surface every agent speaks. Each RPC is
    wrapped by an Envelope carrying trace_id, source, target, capability
    and an HMAC signature so the server can authenticate and authorize
    before dispatch.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DispatchIntent = channel.unary_unary(
                '/cognos.ipc.v1.CognosIpc/DispatchIntent',
                request_serializer=cognos__pb2.Intent.SerializeToString,
                response_deserializer=cognos__pb2.IntentResponse.FromString,
                _registered_method=True)
        self.QueryMemory = channel.unary_unary(
                '/cognos.ipc.v1.CognosIpc/QueryMemory',
                request_serializer=cognos__pb2.MemoryQuery.SerializeToString,
                response_deserializer=cognos__pb2.MemoryResult.FromString,
                _registered_method=True)
        self.HalGate = channel.unary_unary(
                '/cognos.ipc.v1.CognosIpc/HalGate',
                request_serializer=cognos__pb2.HalGateRequest.SerializeToString,
                response_deserializer=cognos__pb2.HalGateResponse.FromString,
                _registered_method=True)
        self.ResourceHint = channel.unary_unary(
                '/cognos.ipc.v1.CognosIpc/ResourceHint',
                request_serializer=cognos__pb2.ResourceHint.SerializeToString,
                response_deserializer=cognos__pb2.Heartbeat.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cognos.ipc.v1.CognosIpc/Heartbeat',
                request_serializer=cognos__pb2.Heartbeat.SerializeToString,
                response_deserializer=cognos__pb2.Heartbeat.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/cognos.ipc.v1.CognosIpc/StreamEvents',
                request_serializer=cognos__pb2.Heartbeat.SerializeToString,
                response_deserializer=cognos__pb2.Event.FromString,
                _registered_method=True)
        self.GetPipelineMetrics = channel.unary_unary(
                '/cognos.ipc.v1.CognosIpc/GetPipelineMetrics',
                request_serializer=cognos__pb2.PipelineMetricsRequest.SerializeToString,
                response_deserializer=cognos__pb2.PipelineMetrics.FromString,
                _registered_method=True)


class CognosIpcServicer:
    """─── Top-level service ───────────────────────────────────────────────────────
    CognosIpc is the single gRPC surface every agent speaks. Each RPC is
    wrapped by an Envelope carrying trace_id, source, target, capability
    and an HMAC signature so the server can authenticate and authorize
    before dispatch.
    """

    def DispatchIntent(self, request, context):
        """DispatchIntent routes a parsed intent to its target agent(s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMemory(self, request, context):
        """QueryMemory performs a vector + tag search against ANFS / memory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HalGate(self, request, context):
        """HalGate requests a hardware action through the HAL gate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceHint(self, request, context):
        """ResourceHint pushes a scheduling hint to the scheduler daemon.
        Types are fully qualified because the RPC method name collides with the
        `ResourceHint`/`Heartbeat` message names; unqualified references resolve
        to the method symbol first under protoc and fail (see grpc_tools protoc).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat is a bidirectional liveness ping (unused stream direction in v0).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """StreamEvents is a server-streaming RPC used by shells, dashboards
        and observers to subscribe to the global event bus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineMetrics(self, request, context):
        """GetPipelineMetrics returns aggregate HAL / parser / latency counters
        maintained by the serving daemon (HAL, intent-engine, or orchestrator).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CognosIpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DispatchIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchIntent,
                    request_deserializer=cognos__pb2.Intent.FromString,
                    response_serializer=cognos__pb2.IntentResponse.SerializeToString,
            ),
            'QueryMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMemory,
                    request_deserializer=cognos__pb2.MemoryQuery.FromString,
                    response_serializer=cognos__pb2.MemoryResult.SerializeToString,
            ),
            'HalGate': grpc.unary_unary_rpc_method_handler(
                    servicer.HalGate,
                    request_deserializer=cognos__pb2.HalGateRequest.FromString,
                    response_serializer=cognos__pb2.HalGateResponse.SerializeToString,
            ),
            'ResourceHint': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceHint,
                    request_deserializer=cognos__pb2.ResourceHint.FromString,
                    response_serializer=cognos__pb2.Heartbeat.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cognos__pb2.Heartbeat.FromString,
                    response_serializer=cognos__pb2.Heartbeat.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=cognos__pb2.Heartbeat.FromString,
                    response_serializer=cognos__pb2.Event.SerializeToString,
            ),
            'GetPipelineMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineMetrics,
                    request_deserializer=cognos__pb2.PipelineMetricsRequest.FromString,
                    response_serializer=cognos__pb2.PipelineMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognos.ipc.v1.CognosIpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognos.ipc.v1.CognosIpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CognosIpc:
    """─── Top-level service ───────────────────────────────────────────────────────
    CognosIpc is the single gRPC surface every agent speaks. Each RPC is
    wrapped by an Envelope carrying trace_id, source, target, capability
    and an HMAC signature so the server can authenticate and authorize
    before dispatch.
    """

    @staticmethod
    def DispatchIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/DispatchIntent',
            cognos__pb2.Intent.SerializeToString,
            cognos__pb2.IntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/QueryMemory',
            cognos__pb2.MemoryQuery.SerializeToString,
            cognos__pb2.MemoryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HalGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/HalGate',
            cognos__pb2.HalGateRequest.SerializeToString,
            cognos__pb2.HalGateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResourceHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/ResourceHint',
            cognos__pb2.ResourceHint.SerializeToString,
            cognos__pb2.Heartbeat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/Heartbeat',
            cognos__pb2.Heartbeat.SerializeToString,
            cognos__pb2.Heartbeat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/StreamEvents',
            cognos__pb2.Heartbeat.SerializeToString,
            cognos__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognos.ipc.v1.CognosIpc/GetPipelineMetrics',
            cognos__pb2.PipelineMetricsRequest.SerializeToString,
            cognos__pb2.PipelineMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
